# Generated by Django 3.2 on 2021-08-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='cache',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否缓存'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='component',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='组件类型'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='external_link',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否外链'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否隐藏'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent',
            field=models.IntegerField(blank=True, default=0, verbose_name='菜单层级'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='path',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='路由路径'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='权限标识'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='redirect',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='跳转地址'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='type',
            field=models.IntegerField(blank=True, default=0, verbose_name='权限类型'),
        ),
    ]
