# Generated by Django 3.2 on 2021-08-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='role',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='role',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='update_time',
        ),
    ]
