# Generated by Django 3.2 on 2021-08-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210821_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='job_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='staff_id',
        ),
    ]
