# Generated by Django 3.2 on 2021-08-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20210823_2319'),
        ('system', '0005_alter_userprofile_phone'),
    ]

    operations = [
    ]
