# Generated by Django 3.2 on 2021-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_merge_20210824_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['sort'], 'verbose_name': '角色信息', 'verbose_name_plural': '角色信息'},
        ),
        migrations.AddField(
            model_name='role',
            name='key',
            field=models.CharField(default='', max_length=64, verbose_name='角色权限标识'),
        ),
        migrations.AddField(
            model_name='role',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='显示顺序'),
        ),
    ]
